# Generated by Django 3.2.12 on 2025-04-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSetting',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('group', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientsetting',
            },
        ),
    ]
