# Generated by Django 3.2.12 on 2025-06-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MSSQLConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='default', max_length=100)),
                ('driver', models.CharField(default='ODBC Driver 17 for SQL Server', max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField(default=1433)),
                ('database', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('schema', models.CharField(default='dbo', max_length=100)),
                ('table_name', models.CharField(default='ChargerTankHistory', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
