# Generated by Django 3.2.12 on 2025-04-18 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargerTankStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=10, unique=True)),
                ('RecDT', models.DateTimeField(default=django.utils.timezone.now)),
                ('EnvTemp', models.IntegerField(blank=True, null=True)),
                ('Charger01_Status', models.BooleanField(blank=True, null=True)),
                ('Charger02_Status', models.BooleanField(blank=True, null=True)),
                ('Charger03_Status', models.BooleanField(blank=True, null=True)),
                ('Charger04_Status', models.BooleanField(blank=True, null=True)),
                ('Charger05_Status', models.BooleanField(blank=True, null=True)),
                ('Charger06_Status', models.BooleanField(blank=True, null=True)),
                ('Charger07_Status', models.BooleanField(blank=True, null=True)),
                ('Charger08_Status', models.BooleanField(blank=True, null=True)),
                ('Charger09_Status', models.BooleanField(blank=True, null=True)),
                ('Charger10_Status', models.BooleanField(blank=True, null=True)),
                ('Charger11_Status', models.BooleanField(blank=True, null=True)),
                ('Charger12_Status', models.BooleanField(blank=True, null=True)),
                ('Charger13_Status', models.BooleanField(blank=True, null=True)),
                ('Charger14_Status', models.BooleanField(blank=True, null=True)),
                ('Charger15_Status', models.BooleanField(blank=True, null=True)),
                ('Charger16_Status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'charger_tank_status',
            },
        ),
        migrations.CreateModel(
            name='ChargerTankHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=10)),
                ('Temptype', models.IntegerField()),
                ('RecDT', models.DateTimeField(default=django.utils.timezone.now)),
                ('S01', models.IntegerField(blank=True, null=True)),
                ('S02', models.IntegerField(blank=True, null=True)),
                ('S03', models.IntegerField(blank=True, null=True)),
                ('S04', models.IntegerField(blank=True, null=True)),
                ('S05', models.IntegerField(blank=True, null=True)),
                ('S06', models.IntegerField(blank=True, null=True)),
                ('S07', models.IntegerField(blank=True, null=True)),
                ('S08', models.IntegerField(blank=True, null=True)),
                ('S09', models.IntegerField(blank=True, null=True)),
                ('S10', models.IntegerField(blank=True, null=True)),
                ('S11', models.IntegerField(blank=True, null=True)),
                ('S12', models.IntegerField(blank=True, null=True)),
                ('S13', models.IntegerField(blank=True, null=True)),
                ('S14', models.IntegerField(blank=True, null=True)),
                ('S15', models.IntegerField(blank=True, null=True)),
                ('S16', models.IntegerField(blank=True, null=True)),
                ('S17', models.IntegerField(blank=True, null=True)),
                ('S18', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'charger_tank_history',
                'unique_together': {('Location', 'Temptype', 'RecDT')},
            },
        ),
        migrations.CreateModel(
            name='ChargerTankCurrent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=10)),
                ('Temptype', models.IntegerField()),
                ('RecDT', models.DateTimeField(default=django.utils.timezone.now)),
                ('S01', models.IntegerField(blank=True, null=True)),
                ('S02', models.IntegerField(blank=True, null=True)),
                ('S03', models.IntegerField(blank=True, null=True)),
                ('S04', models.IntegerField(blank=True, null=True)),
                ('S05', models.IntegerField(blank=True, null=True)),
                ('S06', models.IntegerField(blank=True, null=True)),
                ('S07', models.IntegerField(blank=True, null=True)),
                ('S08', models.IntegerField(blank=True, null=True)),
                ('S09', models.IntegerField(blank=True, null=True)),
                ('S10', models.IntegerField(blank=True, null=True)),
                ('S11', models.IntegerField(blank=True, null=True)),
                ('S12', models.IntegerField(blank=True, null=True)),
                ('S13', models.IntegerField(blank=True, null=True)),
                ('S14', models.IntegerField(blank=True, null=True)),
                ('S15', models.IntegerField(blank=True, null=True)),
                ('S16', models.IntegerField(blank=True, null=True)),
                ('S17', models.IntegerField(blank=True, null=True)),
                ('S18', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'charger_tank_current',
                'unique_together': {('Location', 'Temptype')},
            },
        ),
    ]
