# Generated by Django 3.2.12 on 2025-04-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charger_tank', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chargertankcurrent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='chargertankhistory',
            unique_together=set(),
        ),
    ]
