# Generated by Django 3.2.12 on 2025-04-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger_tank', '0002_auto_20250418_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargertankstatus',
            name='Location',
            field=models.CharField(max_length=10),
        ),
    ]
