# Generated by Django 3.2.12 on 2025-04-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charger_tank', '0003_alter_chargertankstatus_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger01_Status',
            new_name='ChargerStatus01',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger02_Status',
            new_name='ChargerStatus02',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger03_Status',
            new_name='ChargerStatus03',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger04_Status',
            new_name='ChargerStatus04',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger05_Status',
            new_name='ChargerStatus05',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger06_Status',
            new_name='ChargerStatus06',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger07_Status',
            new_name='ChargerStatus07',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger08_Status',
            new_name='ChargerStatus08',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger09_Status',
            new_name='ChargerStatus09',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger10_Status',
            new_name='ChargerStatus10',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger11_Status',
            new_name='ChargerStatus11',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger12_Status',
            new_name='ChargerStatus12',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger13_Status',
            new_name='ChargerStatus13',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger14_Status',
            new_name='ChargerStatus14',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger15_Status',
            new_name='ChargerStatus15',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='Charger16_Status',
            new_name='ChargerStatus16',
        ),
    ]
