# Generated by Django 3.2.12 on 2025-04-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charger_tank', '0004_auto_20250418_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus01',
            new_name='Charger_Status01',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus02',
            new_name='Charger_Status02',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus03',
            new_name='Charger_Status03',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus04',
            new_name='Charger_Status04',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus05',
            new_name='Charger_Status05',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus06',
            new_name='Charger_Status06',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus07',
            new_name='Charger_Status07',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus08',
            new_name='Charger_Status08',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus09',
            new_name='Charger_Status09',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus10',
            new_name='Charger_Status10',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus11',
            new_name='Charger_Status11',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus12',
            new_name='Charger_Status12',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus13',
            new_name='Charger_Status13',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus14',
            new_name='Charger_Status14',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus15',
            new_name='Charger_Status15',
        ),
        migrations.RenameField(
            model_name='chargertankstatus',
            old_name='ChargerStatus16',
            new_name='Charger_Status16',
        ),
    ]
