# Generated by Django 3.2.12 on 2025-04-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger_tank', '0006_auto_20250418_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargertankcurrent',
            name='s08',
        ),
        migrations.RemoveField(
            model_name='chargertankhistory',
            name='s08',
        ),
        migrations.AddField(
            model_name='chargertankcurrent',
            name='s08_1',
            field=models.IntegerField(blank=True, db_column='S08_1', null=True),
        ),
        migrations.AddField(
            model_name='chargertankcurrent',
            name='s08_2',
            field=models.IntegerField(blank=True, db_column='S08_2', null=True),
        ),
        migrations.AddField(
            model_name='chargertankhistory',
            name='s08_1',
            field=models.IntegerField(blank=True, db_column='S08_1', null=True),
        ),
        migrations.AddField(
            model_name='chargertankhistory',
            name='s08_2',
            field=models.IntegerField(blank=True, db_column='S08_2', null=True),
        ),
    ]
