# Generated by Django 3.2.12 on 2025-04-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger_tank', '0007_auto_20250422_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargertankcurrent',
            name='s08_1',
        ),
        migrations.RemoveField(
            model_name='chargertankcurrent',
            name='s08_2',
        ),
        migrations.RemoveField(
            model_name='chargertankhistory',
            name='s08_1',
        ),
        migrations.RemoveField(
            model_name='chargertankhistory',
            name='s08_2',
        ),
        migrations.AddField(
            model_name='chargertankcurrent',
            name='s08',
            field=models.IntegerField(blank=True, db_column='S08', null=True),
        ),
        migrations.AddField(
            model_name='chargertankhistory',
            name='s08',
            field=models.IntegerField(blank=True, db_column='S08', null=True),
        ),
    ]
