# Generated by Django 3.2.12 on 2025-05-16 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charger_tank', '0008_auto_20250424_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargerTankStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(db_column='Location', max_length=10)),
                ('record_datetime', models.DateTimeField(db_column='RecDT', default=django.utils.timezone.now)),
                ('env_temp', models.IntegerField(blank=True, db_column='EnvTemp', null=True)),
                ('charger_status01', models.BooleanField(blank=True, db_column='ChargerStatus01', null=True)),
                ('charger_status02', models.BooleanField(blank=True, db_column='ChargerStatus02', null=True)),
                ('charger_status03', models.BooleanField(blank=True, db_column='ChargerStatus03', null=True)),
                ('charger_status04', models.BooleanField(blank=True, db_column='ChargerStatus04', null=True)),
                ('charger_status05', models.BooleanField(blank=True, db_column='ChargerStatus05', null=True)),
                ('charger_status06', models.BooleanField(blank=True, db_column='ChargerStatus06', null=True)),
                ('charger_status07', models.BooleanField(blank=True, db_column='ChargerStatus07', null=True)),
                ('charger_status08', models.BooleanField(blank=True, db_column='ChargerStatus08', null=True)),
                ('charger_status09', models.BooleanField(blank=True, db_column='ChargerStatus09', null=True)),
                ('charger_status10', models.BooleanField(blank=True, db_column='ChargerStatus10', null=True)),
                ('charger_status11', models.BooleanField(blank=True, db_column='ChargerStatus11', null=True)),
                ('charger_status12', models.BooleanField(blank=True, db_column='ChargerStatus12', null=True)),
                ('charger_status13', models.BooleanField(blank=True, db_column='ChargerStatus13', null=True)),
                ('charger_status14', models.BooleanField(blank=True, db_column='ChargerStatus14', null=True)),
                ('charger_status15', models.BooleanField(blank=True, db_column='ChargerStatus15', null=True)),
                ('charger_status16', models.BooleanField(blank=True, db_column='ChargerStatus16', null=True)),
            ],
            options={
                'db_table': 'charger_tank_status_history',
            },
        ),
    ]
