# Generated by Django 3.2.12 on 2025-06-16 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charger_tank', '0009_chargertankstatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargerTankHistory5Min',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(db_column='Location', max_length=10)),
                ('temp_type', models.IntegerField(db_column='Temptype')),
                ('record_datetime', models.DateTimeField(db_column='RecDT', default=django.utils.timezone.now)),
                ('s01', models.IntegerField(blank=True, db_column='S01', null=True)),
                ('s02', models.IntegerField(blank=True, db_column='S02', null=True)),
                ('s03', models.IntegerField(blank=True, db_column='S03', null=True)),
                ('s04', models.IntegerField(blank=True, db_column='S04', null=True)),
                ('s05', models.IntegerField(blank=True, db_column='S05', null=True)),
                ('s06', models.IntegerField(blank=True, db_column='S06', null=True)),
                ('s07', models.IntegerField(blank=True, db_column='S07', null=True)),
                ('s08', models.IntegerField(blank=True, db_column='S08', null=True)),
                ('s09', models.IntegerField(blank=True, db_column='S09', null=True)),
                ('s10', models.IntegerField(blank=True, db_column='S10', null=True)),
                ('s11', models.IntegerField(blank=True, db_column='S11', null=True)),
                ('s12', models.IntegerField(blank=True, db_column='S12', null=True)),
                ('s13', models.IntegerField(blank=True, db_column='S13', null=True)),
                ('s14', models.IntegerField(blank=True, db_column='S14', null=True)),
                ('s15', models.IntegerField(blank=True, db_column='S15', null=True)),
                ('s16', models.IntegerField(blank=True, db_column='S16', null=True)),
                ('s17', models.IntegerField(blank=True, db_column='S17', null=True)),
                ('s18', models.IntegerField(blank=True, db_column='S18', null=True)),
            ],
            options={
                'db_table': 'charger_tank_history_5min',
            },
        ),
    ]
